version: '3.8'
services:
    architecture-portal:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    redis:
        image: redis/redis-stack:latest
        container_name: redis
        ports:
            - '127.0.0.1:6379:6379'
